# 项目相关配置
ruoyi:
  # 名称
  name: RuoYi
  # 版本
  version: 3.8.9
  # 版权年份
  copyrightYear: 2025
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: D:/ruoyi/uploadPath
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数字计算 char 字符验证
  captchaType: math

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8090
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

alipay:
  serverUrl: "https://openapi.alipay.com/gateway.do"
  appId: "2021005127643793"
  privateKey: "MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCEr5L/cd3t9sHRBhhCx0eq8thGeqdAZyg0xP6oIGPX+4U9AC4eroKkxOCM8wv9AaF/58ckd2BVQn8FT5p4Af16bh0ytzLHd+QixdmsF92yknTstXLBvu5hDZ2F3Si3rYLwiL8BDdKAdtoyNT5bW4+G8SSHci9PjmOV3qhPm9TaPmpHiRCOkwIwIRIdiSKoMoM4J1uIOWVXbiY12dwEdCJt90pACwV9sxsHpZIF2nuv0jyH+GfdcuIRT+66jV814+m3JZZltYiWxM868KQIra+8JYV6b5N0OKOEfcNzmN+COmOyXBJmZ/8QxIPo+62zFHSBg7MEXHCEMIxKLhJYMaqXAgMBAAECggEAOzo8PbZQQFazcWBtF/HoddBs5hj962ugsN12Zwn+R3zIntAjxiJTwsT3DzO2mDtQIc4OQKLg524FUROVehg5U5svgWHxUsSbm0IBxiXpGjrx4m+kSAO4WK5BMG3mLQdQuZnw2MGYwytKfrrxmMooKS4fBi7cG4ENxupa6x4+RySMYNW/SR6NW+HTuOsl4VdrEOTKM7pnxz7adRPjgLFPFyvAwy31WLv6glAkcOz4Mxbyosvuqg0ShKGqzurSV4+TOapFD6xs6va3ljqoV9vPvoqgFAMOZXGYZqVNcLb+UJsN/+CKHN+zwEGYDPfJYmzOxf/kZV6e5iUR/Ul2vqyxwQKBgQDEcEEhFREzovju8bd5VmZCqRx5Wj8HVP4Alavz9e9Y3fes0rbfA8pTy9iBxS/KSW1qOwToh9Xy1cniS2TVBUGVhryhVnnT7//ZXV+ikVRXwYocBsjA7WZEFTnBjrtnzfeOs0QkcimUgXhkfmxaem4IksA/BKJBf7ohd5mww2568QKBgQCs6sbpGKuqyo99TKCdOLBVRzvKq4f6sH0eU/kdn/g/yJMfEqUpcgoSzd2zgDQpD0/bTH27Yi6CmdbyeUuRStpGhtsviKX0VCDyCrOek3khbCfyVBF+JU0mW+BMZjw2uSHRc/LlRz1F7b5EbYTkEKOcXu1d3ZJ8rx+oxq7g9WUuBwKBgQCcdah6WBROY4UQlDgFjfp/J8EFKws+pMR25L+D3aPYzVrjLSX4tUUmvxrgKZWp8hgS35VGPEL9Wqik9FYIkVouZZXCj2UTmHnYwFVW35glGYMOVZz6hVvJ6HoLH8tGn7eI0mH5AXD61rB0onldC1yuuWwkBWXS84/l7iPctZw+kQKBgQCXgYYTCoivNpgOwysfVmI59hYPd8fHAQg/oHfvWxCaYlV1rlKEQ+VLoJEWC8ioCUCA9z5bBqWVzNEm1tw9S4aAsPwvY910fJn5OSM0WCaUAD3n93z0OB6m821Nw24SzJcy/BLgjVDEipBhSExdv656/jmgOtl04cQtjxf/B0RF1QKBgDrWd1+f+kWQE9RXPd19vzUrKJR0b2XjHCoZ+suCu2hwdfFrBs6AIi0MBO7Zvc4IJU2UnNQaFO7ps7E7KfSJghG9OMv4Lr+ajmvSmWvttbGmbY0ibtQ3uRNG2SUzhKaiNMDiHLwDLLTtTCPQERRpEI/Sr2RwcxmnSRZ46XFZpHKA"
  alipayPublicKey: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAosiOhzYC4PAAv2DKPlWcAzZ9FjfKqz3Fnw9TeCkpoB2esA6MewrKQXmLEU9fTWsZAJfvR7WRwm9hQxmwfpQyw9+jwipK1+kuryy//ZDKx+FxULFjq+rfYO882mlN8PGFa+rElfgSrcYDEj8p878G4RC5pP+UsbUDNg/SdAE4FOSi1X2EoV+KsF8ikmxyskTsdULwiFXcyzSz39TkuCHqiNnXiUM6HidU7p6ERAbkGg7blzu3QwfyvW5BCcL6AxY9hZ25/pi7sTA7a3/vqgcesKyYYaziCP+f7bkFy7YKXujsMvOJ90+WozUDzwLvAyOdO9OF3cnfcIfKtFWiKjvyKwIDAQAB"
  format: "json"
  charset: "UTF-8"
  signType: "RSA2"
  notifyUrl: "http://119.3.173.120:8090/api/pay/alipaywapnotify"


# 日志配置
logging:
  level:
    com.ruoyi: debug
    org.springframework: warn

# 用户配置
user:
  password:
    # 密码最大错误次数
    maxRetryCount: 5
    # 密码锁定时间（默认10分钟）
    lockTime: 10

# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: druid
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # redis 配置
  redis:
    # 地址
    host: 119.3.173.120
    # 端口，默认为6379
    port: 26739
    # 数据库索引
    database: 0
    # 密码
    password: CPRexmLpCbp4hhf3
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 120

# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.ruoyi.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /dev-api

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*
